import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface PdfCard {
  name: string;
  setCode?: string | null;
  rarity?: string | null;
  condition: string;
  finalPrice: number;
}

interface PdfInput {
  transactionNo: string;
  createdAt: Date;
  customerName?: string | null;
  customerPhone?: string | null;
  customerIdLast4?: string | null;
  staffName?: string | null;
  supervisorName?: string | null;
  cards: PdfCard[];
  totalAmount: number;
  signatureDataUrl?: string | null;
}

/**
 * Generates the buyback agreement PDF and returns it as a Uint8Array suitable
 * for download from a Next.js route handler.
 */
export function generateBuybackPdf(input: PdfInput): Uint8Array {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("CardMaster Pro - Buyback Agreement", margin, 60);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Transaction No: ${input.transactionNo}`, margin, 80);
  doc.text(
    `Date: ${input.createdAt.toLocaleString("en-GB")}`,
    pageWidth - margin,
    80,
    { align: "right" },
  );

  doc.setDrawColor(180);
  doc.line(margin, 90, pageWidth - margin, 90);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Customer Information", margin, 110);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Name: ${input.customerName || "_________________"}`, margin, 128);
  doc.text(`Phone: ${input.customerPhone || "_________________"}`, margin + 220, 128);
  doc.text(`ID (last 4): ${input.customerIdLast4 || "____"}`, margin + 420, 128);
  doc.text(`Staff: ${input.staffName || "_________"}`, margin, 144);
  doc.text(`Supervisor: ${input.supervisorName || "_________"}`, margin + 220, 144);

  autoTable(doc, {
    startY: 165,
    head: [["#", "Card Name", "Set Code", "Rarity", "Cond.", "Amount (HKD)"]],
    body: input.cards.map((c, i) => [
      String(i + 1),
      c.name,
      c.setCode || "—",
      c.rarity || "—",
      c.condition,
      c.finalPrice.toLocaleString(),
    ]),
    styles: { fontSize: 9, cellPadding: 5 },
    headStyles: { fillColor: [30, 41, 59], textColor: 255 },
    columnStyles: {
      0: { cellWidth: 28, halign: "center" },
      4: { halign: "center" },
      5: { halign: "right" },
    },
    margin: { left: margin, right: margin },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tableEnd = (doc as any).lastAutoTable?.finalY || 200;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(
    `TOTAL: HKD ${input.totalAmount.toLocaleString()}`,
    pageWidth - margin,
    tableEnd + 24,
    { align: "right" },
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Legal Terms & Customer Acknowledgement", margin, tableEnd + 60);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  const terms = [
    "1. The Seller warrants that the cards listed above are their lawful property, free of any liens or claims.",
    "2. The Seller confirms that the cards are authentic and have not been knowingly altered, counterfeited, or tampered with.",
    "3. Once this agreement is signed and the agreed amount has been paid, the sale is final and irrevocable.",
    "4. CardMaster Pro reserves the right to verify the authenticity and condition of all cards. Misrepresentation may result in legal action.",
    "5. The Seller acknowledges that the offered prices reflect current market conditions and are determined by our proprietary pricing engine.",
    "6. Customer personal data is collected solely for transaction records and regulatory compliance, and will be handled in accordance with the PDPO (Cap. 486).",
  ];
  let y = tableEnd + 76;
  for (const line of terms) {
    const wrapped = doc.splitTextToSize(line, pageWidth - margin * 2);
    doc.text(wrapped, margin, y);
    y += wrapped.length * 10 + 4;
  }

  const sigY = Math.max(y + 30, doc.internal.pageSize.getHeight() - 140);
  doc.setDrawColor(120);
  doc.line(margin, sigY, margin + 220, sigY);
  doc.line(pageWidth - margin - 220, sigY, pageWidth - margin, sigY);
  doc.setFontSize(9);
  doc.text("Customer Signature", margin, sigY + 14);
  doc.text("Store Representative", pageWidth - margin - 220, sigY + 14);

  if (input.signatureDataUrl && input.signatureDataUrl.startsWith("data:image")) {
    try {
      doc.addImage(input.signatureDataUrl, "PNG", margin, sigY - 50, 200, 48);
    } catch (e) {
      console.warn("Failed to embed signature image", e);
    }
  }

  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text(
    `Generated by CardMaster Pro · ${new Date().toISOString()}`,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 20,
    { align: "center" },
  );

  return new Uint8Array(doc.output("arraybuffer"));
}
